services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge